name: CompleteCICD

on:
    push:
    pull_request:

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: echo "Building application"
        
    
    docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Docker Login
              run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
            
            - name: Build Image
              run: docker build -t ${{secrets.DOCKER_USERNAME}}/complete-cicd:v1 .

            - name: Push Docker hub
              run: docker push ${{secrets.DOCKER_USERNAME}}/complete-cicd:v1
              
            - name: Github login
              run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u "${{github.actor}}" --password-stdin
              
            - name: tag GHCR
              run: docker tag ${{secrets.DOCKER_USERNAME}}/complete-cicd:v1 ghcr.io/${{github.actor}}/complete-cicd:v1
            
            - name: Push GHCR
              run: docker push ghcr.io/${{github.actor}}/complete-cicd:v1
            
            - name: Github logout
              run: docker logout ghcr.io
            
            - name: Docker pulling without login
              run: docker pull ghcr.io/${{github.actor}}/complete-cicd:v1
            
            - name: docker pulling image from ghcr.io
              run: docker pull ghcr.io/${{github.actor}}/complete-cicd:v1
        
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying Application"